version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    build: docker/db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
